apiVersion: v1
kind: Service
metadata:
  name: cartservice
spec:
  type: LoadBalancer
  selector:
    app: cartservice
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  labels:
    app: cartservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
        - name: cartservice
          image: docker.io/malindupanchala/ctse_cart_service:latest
          ports:
            - containerPort: 5000
          env:
            - name: URL
              value: mongodb+srv://DBUSER:dbuser@project.zqftq.mongodb.net/CTSEAssingementTwo?retryWrites=true&w=majority
