apiVersion: v1
kind: Service
metadata:
  name: orderservice
spec:
  type: LoadBalancer
  selector:
    app: orderservice
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: orderservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orderservice
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      containers:
        - name: orderservice
          image: docker.io/ab98/orderservice:latest
          ports:
            - containerPort: 5050
          env:
            - name: URL
              value: mongodb+srv://DBUSER:dbuser@project.zqftq.mongodb.net/CTSEAssingementTwo?retryWrites=true&w=majority
