apiVersion: v1
kind: Service
metadata:
  name: productservice
spec:
  type: LoadBalancer
  selector:
    app: productservice
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: productservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: productservice
  template:
    metadata:
      labels:
        app: productservice
    spec:
      containers:
        - name: productservice
          image: docker.io/madukanuwantha/productservice:latest
          ports:
            - containerPort: 5000
          env:
            - name: URL
              value: mongodb+srv://DBUSER:dbuser@project.zqftq.mongodb.net/CTSEAssingementTwo?retryWrites=true&w=majority
