name:  CI/CD Pipeline // CTSE ASSIGNMENT

on:
  push:
    branches: [ master ]
  pull_request: 
    branches: [ master ]
  workflow_dispatch:

env:
  MALINDU_DOCKER_USERNAME: ${{secrets.MALINDU_DOCKER_USERNAME}}
  MALINDU_DOCKER_PASSWORD: ${{secrets.MALINDU_DOCKER_PASSWORD}}
  MALINDU_DOCKER_REPOSITORY: ${{secrets.MALINDU_DOCKER_REPOSITORY}}

jobs:
  CartService:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: | 
        docker login -u $MALINDU_DOCKER_USERNAME -p $MALINDU_DOCKER_PASSWORD
    - name: CartService docker image building...
      run: |
        cd CartService/
        docker build -f ./Dockerfile -t $MALINDU_DOCKER_USERNAME/$MALINDU_DOCKER_REPOSITORY ./
    - name: Pushing build to docker hub...
      run: docker push $MALINDU_DOCKER_USERNAME/$MALINDU_DOCKER_REPOSITORY:latest
